# Generated by Django 5.1.2 on 2024-12-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_used_vehicle', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in km')),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], max_length=50)),
                ('power', models.PositiveIntegerField(help_text='Power in hp')),
                ('gearbox', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Other', 'Other')], max_length=50)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('doors', models.CharField(choices=[('2/3', '2/3'), ('4/5', '4/5'), ('Other', 'Other')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='offer_images/')),
                ('short_description', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
